#!/bin/bash

# NEW ONE THAT I'M WORKING ON NOW!!!

mainstart=$(date +%s)

sudo sed -i "s/#precedence ::ffff:0:0\/96  100/precedence ::ffff:0:0\/96  100/" /etc/gai.conf

# Upgrade The Base Packages

export DEBIAN_FRONTEND=noninteractive

sudo bash -c 'echo -e "[user]\n\tname = abc\n\temail = root@localhost.com" > /root/.gitconfig'

wget -qO ee rt.cx/ee && sudo bash ee

y | y | ee site create example.com --wpredis --php7

mainend=$(date +%s)
totalruntime=$((mainend-mainstart))

echo "Total Provosioning Proceesing Time: $totalruntime seconds!"

echo "Total Provosioning Proceesing Time: $totalruntime seconds!" > /tmp/resty-build.log
