#!/bin/bash

mainstart=$(date +%s)

PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:$PATH

serverIP=$(curl http://ip4.ident.me 2>/dev/null)

gridpanetoken=$(awk '{print $1; exit}' /root/gridpane.token)

GPURL=$(awk '{print $1; exit}' /root/grid.source)

export DEBIAN_FRONTEND=noninteractive

sudo sed -i "s/#precedence ::ffff:0:0\/96  100/precedence ::ffff:0:0\/96  100/" /etc/gai.conf

ProgressCurl=$(curl -d '{"percentage":"11", "detail":"Installing the basics, please be patient...", "server_ip":"'$serverIP'"}' -H "Content-Type: application/json" -X POST https://$GPURL/api/build-progress?api_token=$gridpanetoken 2>&1)

mkdir -p /opt/gridpane/logs

touch /opt/gridpane/logs/plaid-build.log

chmod +x /opt/go-plaid/apt-get && cp /opt/go-plaid/apt-get /usr/local/sbin/apt-get

wget -qO go-plaid gridpane.com/go-plaid/go-plaid && sudo bash go-plaid 3 > /opt/gridpane/logs/random-build.log

sleep 10

echo "**** Checking NGINX Install... ****** " |& tee -a /opt/gridpane/logs/plaid-build.log 

nginx -V |& tee -a /opt/gridpane/logs/plaid-build.log 

eNginxVersion=$(nginx -V)

if [[ $eNginxVersion == *"can be found in the following packages"* ]] || [[ $eNginxVersion == *"command not found"* ]] || [[ $eNginxVersion == *"nginx/1.10.3"* ]] 
then
	echo "***** LOOKS LIKE WE HAVE AN NGINX ERROR!!! ******" |& tee -a /opt/gridpane/logs/plaid-build.log 
	
	sudo dpkg --configure -a |& tee -a /opt/gridpane/logs/plaid-build.log
	
	sudo apt-get -y install nginx |& tee -a /opt/gridpane/logs/plaid-build.log
	
	sudo cp -R /opt/plaid/templates/nginx/common /etc/nginx/common
	sudo cp -R /opt/plaid/templates/nginx/conf.d/* /etc/nginx/conf.d/

	sudo cat /opt/plaid/templates/nginx/nginx.conf > /etc/nginx/nginx.conf
	
	sudo sed -i '/REQUEST_SCHEME/c \fastcgi_param  SCRIPT_FILENAME        $request_filename;' /etc/nginx/fastcgi_params
	sudo sed -i '/REDIRECT_STATUS/a \fastcgi_param   HTTP_PROXY      "";' /etc/nginx/fastcgi_params
	
fi

if [ -f /etc/nginx/nginx.conf ]
then
	
	echo "Nginx.conf is present..." |& tee -a /opt/gridpane/logs/plaid-build.log
	
else
	echo "***** LOOKS LIKE NGINX.CONF is MISSING!!! ******" |& tee -a /opt/gridpane/logs/plaid-build.log
	
	sudo dpkg --configure -a |& tee -a /opt/gridpane/logs/plaid-build.log
	
	sudo apt-get -y install nginx |& tee -a /opt/gridpane/logs/plaid-build.log
	
	sudo cp -R /opt/plaid/templates/nginx/common /etc/nginx/common
	sudo cp -R /opt/plaid/templates/nginx/conf.d/* /etc/nginx/conf.d/

	sudo cat /opt/plaid/templates/nginx/nginx.conf > /etc/nginx/nginx.conf
	
	sudo sed -i '/REQUEST_SCHEME/c \fastcgi_param  SCRIPT_FILENAME        $request_filename;' /etc/nginx/fastcgi_params
	sudo sed -i '/REDIRECT_STATUS/a \fastcgi_param   HTTP_PROXY      "";' /etc/nginx/fastcgi_params
	
fi

sleep 5

echo "**** Checking MYSQL Install... ****** " |& tee -a /opt/gridpane/logs/plaid-build.log 

mysql -V |& tee -a /opt/gridpane/logs/plaid-build.log 

mySQLVersion=$(mysql -V)

if [[ $mySQLVersion == *"can be found in the following packages"* ]]
then
	
	echo "***** LOOKS LIKE WE HAVE AN MYSQL ERROR!!! ******" |& tee -a /opt/gridpane/logs/plaid-build.log 
	
	sudo dpkg --configure -a |& tee -a /opt/gridpane/logs/plaid-build.log
	
	sudo apt-get -y install mariadb-server |& tee -a /opt/gridpane/logs/plaid-build.log
	
	sudo apt-get -y install mariadb-client |& tee -a /opt/gridpane/logs/plaid-build.log
	
fi

sleep 5

if [ -f /var/run/mysqld/mysqld.sock ]
then
	
	echo "Looks like mariadb server is installed by checking the file /var/run/mysqld/mysqld.sock" |& tee -a /opt/gridpane/logs/plaid-build.log
	
else
	sudo dpkg --configure -a |& tee -a /opt/gridpane/logs/plaid-build.log
	
	sudo apt-get -y install mariadb-server |& tee -a /opt/gridpane/logs/plaid-build.log
	
	sudo apt-get -y install mariadb-client |& tee -a /opt/gridpane/logs/plaid-build.log
	
fi

sleep 5

echo "**** Checking PHP Install... ****** " |& tee -a /opt/gridpane/logs/plaid-build.log 

service php7.2-fpm status |& tee -a /opt/gridpane/logs/plaid-build.log

checkPHPVersion=$(service php7.2-fpm status)

if [[ $checkPHPVersion == *"Reason: No such file or directory"* ]]
then
	
	echo "***** LOOKS LIKE WE HAVE AN PHP ERROR!!! ******" |& tee -a /opt/gridpane/logs/plaid-build.log
	
	ver=7.2
	
	sudo dpkg --configure -a |& tee -a /opt/gridpane/logs/plaid-build.log
	
	sudo apt-get -y install php${ver}-common php${ver}-cli php${ver}-fpm php${ver}-curl php${ver}-gd php${ver}-imap php${ver}-readline php${ver}-recode php${ver}-mysql php${ver}-mbstring php${ver}-bcmath php${ver}-mysql php${ver}-opcache php${ver}-zip php${ver}-xml php${ver}-soap php-imagick graphviz php-pear php-msgpack |& tee -a /opt/gridpane/logs/plaid-build.log
	
fi

ProgressCurl=$(curl -d '{"percentage":"45", "detail":"All your base are belong to us...", "server_ip":"'$serverIP'"}' -H "Content-Type: application/json" -X POST https://$GPURL/api/build-progress?api_token=$gridpanetoken 2>&1)

DEBIAN_FRONTEND=noninteractive apt-get -y -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confold" install software-properties-common libpcre3-dev make git build-essential curl fail2ban gcc ufw unattended-upgrades unzip whois linux-headers-generic libxslt-dev libgeoip-dev zlib1g-dev libreadline-dev libncurses5-dev perl curl patch tar gzip zsh

sleep 2

apt-get update

sleep 5

ProgressCurl=$(curl -d '{"percentage":"67", "detail":"PC LOAD LETTER...", "server_ip":"'$serverIP'"}' -H "Content-Type: application/json" -X POST https://$GPURL/api/build-progress?api_token=$gridpanetoken 2>&1)

wget -qO /opt/gridpane/gpstage2.sh --timeout=15 https://www.dropbox.com/s/llcw4043bkt4gb0/gpstage2.sh

chmod +x /opt/gridpane/gpstage2.sh

mv /opt/gridpane/gpstage2.sh /usr/local/bin/gpstage2
      
mainend=$(date +%s)
totalruntime=$((mainend-mainstart))

echo "Total Provosioning Proceesing Time: $totalruntime seconds!"

echo "Total Provosioning Proceesing Time: $totalruntime seconds!" > /opt/gridpane/total-build.log

curl -d '{"ip_address":"'$serverIP'", "is_provisioned":"1"}' -H "Content-Type: application/json" -X POST https://$GPURL/api/server/provision-status?api_token=$gridpanetoken >> /opt/gridpane/firstcurl.log
